<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Authors>NovoDwarf</Authors>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Fractals\Algebraic\" />
      <Folder Include="Fractals\Stochastic\" />
      <Folder Include="Noises\Hybrid\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MathForge.Core\MathForge.Core.csproj" />
    </ItemGroup>

</Project>
