<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(ProjectTargetFrameworks)</TargetFrameworks>
    </PropertyGroup>
    
    <ItemGroup>
      <Folder Include="Fractals\Algebraic\" />
      <Folder Include="Fractals\Stochastic\" />
      <Folder Include="Noises\Hybrid\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MathForge.Core" Version="1.0.0" />
    </ItemGroup>

</Project>
