<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(ProjectTargetFrameworks)</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
      <EmbeddedResource Update="Resources\Probability.Resources.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Probability.Resources.Designer.cs</LastGenOutput>
      </EmbeddedResource>
  
      <EmbeddedResource Update="Resources\Numerical.Resources.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Numerical.Resources.Designer.cs</LastGenOutput>
      </EmbeddedResource>
  
      <EmbeddedResource Update="Resources\Base.Resources.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Base.Resources.Designer.cs</LastGenOutput>
      </EmbeddedResource>
  
      <EmbeddedResource Update="Resources\Parameters.Resources.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Parameters.Resources.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>
  
    <ItemGroup>
      <Compile Update="Resources\Probability.Resources.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Probability.Resources.resx</DependentUpon>
      </Compile>
      <Compile Update="Resources\Numerical.Resources.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Numerical.Resources.resx</DependentUpon>
      </Compile>
      <Compile Update="Resources\Base.Resources.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Base.Resources.resx</DependentUpon>
      </Compile>
      <Compile Update="Resources\Parameters.Resources.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Parameters.Resources.resx</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="NovoDwarf.Utilities" Version="1.0.0" />
      <PackageReference Include="System.Drawing.Common" Version="11.0.0-rc.1.26425.128" />
    </ItemGroup>
    
</Project>
