<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(ProjectTargetFrameworks)</TargetFrameworks>
        <RootNamespace>MathForge</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Vectors\Double\" />
        <ProjectReference Include="..\MathForge.SourceGenerators\MathForge.SourceGenerators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
    </ItemGroup>
    

</Project>
