<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(ProjectTargetFrameworks)</TargetFrameworks>
    </PropertyGroup>
    
    <ItemGroup Condition="$(TargetFramework) == 'net10.0'">
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
    </ItemGroup>

    <ItemGroup Condition="$(TargetFramework) == 'net11.0'">
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="11.0.0-preview.5.26302.115" />
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\MathForge.Core\MathForge.Core.csproj" />
      <ProjectReference Include="..\MathForge.Probability\MathForge.Probability.csproj" />
    </ItemGroup>

</Project>
