using System.Collections.Immutable;
using System.Text;
using MathForge.SourceGenerators.Diagnostics;
using MathForge.SourceGenerators.Vectors;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MathForge.SourceGenerators.Generators.Vectors;

[Generator(LanguageNames.CSharp)]
public sealed class VectorGenerator : IIncrementalGenerator
{
    private const string AttributeName = "MathForge.Attributes.VectorAttribute";

    private static readonly string[] CoordinateNames = ["X", "Y", "Z", "W"];

    private static readonly SpecialType[] SupportedTypes =
    [
        SpecialType.System_Int32,
        SpecialType.System_Int64,
        SpecialType.System_Single,
        SpecialType.System_Double,
        SpecialType.System_Decimal
    ];

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.ForAttributeWithMetadataName(AttributeName, static (node, _) => node is TypeDeclarationSyntax, static (attributeContext, _) => (INamedTypeSymbol)attributeContext.TargetSymbol);

        context.RegisterSourceOutput(context.CompilationProvider.Combine(candidates.Collect()), static (productionContext, input) => Execute(productionContext, input.Left, input.Right));
    }

    private static void Execute(SourceProductionContext context, Compilation compilation, ImmutableArray<INamedTypeSymbol> candidates)
    {
        var models = CollectModels(context, candidates);

        if (models.Count == 0)
            return;

        var registry = new VectorTypeRegistry(models);
        var operatorEmitter = new VectorOperatorEmitter(registry);
        var conversionEmitter = new VectorConversionEmitter();

        var scalarTypes = SupportedTypes.Select(compilation.GetSpecialType).Cast<ITypeSymbol>().ToArray();

        foreach (var model in models)
        {
            var members = new List<string> { operatorEmitter.Emit(model, models, scalarTypes) };

            foreach (var target in models)
            {
                if (target.Dimension == model.Dimension)
                    continue;

                if (!SymbolEqualityComparer.Default.Equals(target.ScalarType, model.ScalarType))
                    continue;

                members.Add(conversionEmitter.Emit(model, target));
            }

            var body = string.Join("\n\n", members.Where(static member => !string.IsNullOrWhiteSpace(member)));

            var ns = model.Symbol.ContainingNamespace;
            var namespaceDeclaration = ns.IsGlobalNamespace
                ? string.Empty
                : $"namespace {ns.ToDisplayString()};";

            var source = $$"""
                // <auto-generated/>
                #nullable enable

                {{namespaceDeclaration}}

                public readonly partial record struct {{model.Symbol.Name}}
                {
                {{body}}
                }
                """;

            context.AddSource(SymbolHint(model.Symbol), SourceText.From(source, Encoding.UTF8));
        }
    }

    private static List<VectorModel> CollectModels(SourceProductionContext context, ImmutableArray<INamedTypeSymbol> candidates)
    {
        var models = new List<VectorModel>();
        var seenSymbols = new HashSet<string>(StringComparer.Ordinal);

        foreach (var symbol in candidates)
        {
            var symbolKey = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            if (!seenSymbols.Add(symbolKey))
                continue;

            var attribute = symbol.GetAttributes().FirstOrDefault(static a => a.AttributeClass?.ToDisplayString() == AttributeName);

            if (attribute is null || attribute.ConstructorArguments.Length != 1 || attribute.ConstructorArguments[0].Value is not int dimension)
                continue;

            var location = symbol.Locations.FirstOrDefault();

            if (dimension is < 1 or > 4)
            {
                context.ReportDiagnostic(Diagnostic.Create(VectorDiagnostics.InvalidDimension, location, dimension));
                continue;
            }

            if (!IsValidDeclaration(symbol))
            {
                context.ReportDiagnostic(Diagnostic.Create(VectorDiagnostics.InvalidDeclaration, location, symbol.Name)); 
                continue;
            }

            var coordinates = new List<IPropertySymbol>();
            var valid = true;

            for (var i = 0; i < dimension; i++)
            {
                var property = symbol.GetMembers(CoordinateNames[i]).OfType<IPropertySymbol>().FirstOrDefault();

                if (property is null || property.IsStatic || property.Parameters.Length != 0 || property.GetMethod is null || property.DeclaredAccessibility != Accessibility.Public)
                {
                    valid = false;
                    break;
                }

                coordinates.Add(property);
            }

            if (!valid || coordinates.Any(property => !SymbolEqualityComparer.Default.Equals(property.Type, coordinates[0].Type)))
            {
                context.ReportDiagnostic(Diagnostic.Create(VectorDiagnostics.InvalidCoordinates, location, symbol.Name, string.Join(", ", CoordinateNames.Take(dimension))));
                continue;
            }

            var scalarType = coordinates[0].Type;

            if (Generators.NumericTypeRules.GetKind(scalarType) == NumericTypeKind.Unknown)
            {
                context.ReportDiagnostic(Diagnostic.Create(VectorDiagnostics.InvalidNumericType, coordinates[0].Locations.FirstOrDefault() ?? location, scalarType.ToDisplayString()));
                continue;
            }

            models.Add(new VectorModel(symbol, dimension, scalarType, [.. coordinates]));
        }

        return models;
    }

    private static bool IsValidDeclaration(INamedTypeSymbol symbol)
    {
        if (symbol.TypeKind != TypeKind.Struct || !symbol.IsRecord || !symbol.IsReadOnly || symbol.Arity != 0 || symbol.ContainingType is not null || symbol.DeclaredAccessibility != Accessibility.Public)
        {
            return false;
        }

        var declarations = symbol.DeclaringSyntaxReferences
            .Select(reference => reference.GetSyntax())
            .OfType<TypeDeclarationSyntax>()
            .ToArray();

        return declarations.Length > 0 && declarations.All(declaration => declaration.Modifiers.Any(SyntaxKind.PartialKeyword));
    }

    private static string SymbolHint(INamedTypeSymbol symbol)
    {
        var name = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var sanitized = string.Concat(name.Select(static character => char.IsLetterOrDigit(character) ? character : '_'));

        return sanitized + ".VectorOperators.g.cs";
    }
}
