using System.Collections.Immutable;
using System.Text;
using MathForge.SourceGenerators.Diagnostics;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MathForge.SourceGenerators.Generators;

[Generator]
public sealed class EntityParameterGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "MathForge.Core.Attributes.EntityParameterAttribute";



    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var types = context.SyntaxProvider.ForAttributeWithMetadataName(
                AttributeMetadataName,
                static (_, _) => true,
                static (ctx, _) => ctx.TargetSymbol.ContainingType)
            .Collect();

        context.RegisterSourceOutput(types, static (spc, types) =>
        {
            foreach (var type in types.Where(static type => type is not null)
                                      .GroupBy(static type => type!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
                                      .Select(static group => group.First()!))
            {
                Generate(spc, type);
            }
        });
    }

    private static void Generate(SourceProductionContext context, INamedTypeSymbol type)
    {
        if (!IsPartial(type))
        {
            context.ReportDiagnostic(Diagnostic.Create(CoreDiagnostics.ClassMustBePartial, type.Locations.FirstOrDefault(), type.Name));
            return;
        }

        var parameters = GetParameters(type);

        if (parameters.Any(static p => !p.IsWritable))
        {
            foreach (var parameter in parameters.Where(static p => !p.IsWritable))
            {
                context.ReportDiagnostic(Diagnostic.Create(CoreDiagnostics.UnsupportedMember, parameter.Symbol.Locations.FirstOrDefault(), parameter.Symbol.Name));
            }

            return;
        }

        var hintName = $"{GetTypeName(type)}_EntityParameters.g.cs";

        context.AddSource(hintName, SourceText.From(GenerateSource(type, parameters), Encoding.UTF8));
    }

    private static ImmutableArray<Parameter> GetParameters(INamedTypeSymbol type)
    {
        return
        [
            .. type.GetMembers()
                .Select(CreateParameter)
                .Where(static p => p is not null)
                .Select(static p => p!)
                .OrderBy(static p => p.Symbol.Locations.FirstOrDefault()?.SourceSpan.Start ?? int.MaxValue)
        ];
    }

    private static Parameter? CreateParameter(ISymbol member)
    {
        if (!HasAttribute(member))
            return null;

        return member switch
        {
            IPropertySymbol property => new Parameter(property, property.Type, property.SetMethod is not null),
            IFieldSymbol field => new Parameter(field, field.Type, !field.IsReadOnly),
            _ => null
        };
    }

    private static bool HasAttribute(ISymbol symbol)
    {
        return symbol.GetAttributes().Any(static attribute => attribute.AttributeClass?.ToDisplayString() == AttributeMetadataName);
    }

    private static bool IsPartial(INamedTypeSymbol type)
    {
        return type.DeclaringSyntaxReferences
            .Select(static reference => reference.GetSyntax())
            .OfType<ClassDeclarationSyntax>()
            .Any(static declaration => declaration.Modifiers.Any(SyntaxKind.PartialKeyword));
    }

    private static string GenerateSource(INamedTypeSymbol type, ImmutableArray<Parameter> parameters)
    {
        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        var namespaceName = type.ContainingNamespace.IsGlobalNamespace
            ? null
            : type.ContainingNamespace.ToDisplayString();

        if (namespaceName is not null)
        {
            builder.Append("namespace ")
                .Append(namespaceName)
                .AppendLine(";");
            builder.AppendLine();
        }

        builder.Append("partial class ")
            .Append(type.Name)
            .AppendLine();
        builder.AppendLine("{");

        GenerateObjectSet(builder, parameters);
        builder.AppendLine();
        GenerateTypedSet(builder, parameters);

        builder.AppendLine("}");

        return builder.ToString();
    }

    private static void GenerateObjectSet(StringBuilder builder, ImmutableArray<Parameter> parameters)
    {
        builder.AppendLine("    public override void Set(params object[] parameters)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (parameters is null)");
        builder.AppendLine("            throw new global::System.ArgumentNullException(nameof(parameters));");

        builder.AppendLine();

        builder.AppendLine($"        if (parameters.Length != {parameters.Length})");
        builder.AppendLine(
            $"            throw new global::System.ArgumentException(\"Expected {parameters.Length} parameters, got {{parameters.Length}}\", nameof(parameters));");

        builder.AppendLine();

        for (var i = 0; i < parameters.Length; i++)
        {
            var parameter = parameters[i];
            var name = GetParameterName(parameter.Symbol.Name, i);

            builder.Append("        ")
                .Append(GetTypeName(parameter.Type))
                .Append(' ')
                .Append(name)
                .Append(" = ")
                .Append(Convert(parameter.Type, $"parameters[{i}]"))
                .AppendLine(";");
        }

        builder.AppendLine();

        builder.Append("        Set(");

        for (var i = 0; i < parameters.Length; i++)
        {
            if (i > 0)
                builder.Append(", ");

            builder.Append(GetParameterName(parameters[i].Symbol.Name, i));
        }

        builder.AppendLine(");");
        builder.AppendLine("    }");
    }

    private static void GenerateTypedSet(StringBuilder builder, ImmutableArray<Parameter> parameters)
    {
        builder.Append("    public void Set(");

        for (var i = 0; i < parameters.Length; i++)
        {
            if (i > 0)
                builder.Append(", ");

            builder.Append(GetTypeName(parameters[i].Type))
                .Append(' ')
                .Append(GetParameterName(parameters[i].Symbol.Name, i));
        }

        builder.AppendLine(")");
        builder.AppendLine("    {");

        for (var i = 0; i < parameters.Length; i++)
        {
            builder.Append("        ")
                .Append(parameters[i].Symbol.Name)
                .Append(" = ")
                .Append(GetParameterName(parameters[i].Symbol.Name, i))
                .AppendLine(";");
        }

        builder.AppendLine();
        builder.AppendLine("        Validate();");
        builder.AppendLine("    }");
    }

    private static string Convert(ITypeSymbol type, string expression)
    {
        if (type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } nullable)
            return $"({GetTypeName(type)}){Convert(nullable.TypeArguments[0], expression)}";

        var conversion = type.SpecialType switch
        {
            SpecialType.System_Byte =>
                $"global::System.Convert.ToByte({expression})",

            SpecialType.System_SByte =>
                $"global::System.Convert.ToSByte({expression})",

            SpecialType.System_Int16 =>
                $"global::System.Convert.ToInt16({expression})",

            SpecialType.System_UInt16 =>
                $"global::System.Convert.ToUInt16({expression})",

            SpecialType.System_Int32 =>
                $"global::System.Convert.ToInt32({expression})",

            SpecialType.System_UInt32 =>
                $"global::System.Convert.ToUInt32({expression})",

            SpecialType.System_Int64 =>
                $"global::System.Convert.ToInt64({expression})",

            SpecialType.System_UInt64 =>
                $"global::System.Convert.ToUInt64({expression})",

            SpecialType.System_Single =>
                $"global::System.Convert.ToSingle({expression})",

            SpecialType.System_Double =>
                $"global::System.Convert.ToDouble({expression})",

            SpecialType.System_Decimal =>
                $"global::System.Convert.ToDecimal({expression})",

            SpecialType.System_Boolean =>
                $"global::System.Convert.ToBoolean({expression})",

            SpecialType.System_String =>
                $"global::System.Convert.ToString({expression})!",

            SpecialType.System_Char =>
                $"global::System.Convert.ToChar({expression})",

            _ => null
        };

        if (conversion is not null)
            return conversion;

        if (type.TypeKind == TypeKind.Enum)
            return $"({GetTypeName(type)})global::System.Convert.ToInt32({expression})";

        return $"({GetTypeName(type)}){expression}";
    }

    private static string GetTypeName(ITypeSymbol type)
    {
        return type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            .Replace("global::", string.Empty)
            .Replace('.', '_')
            .Replace('<', '_')
            .Replace('>', '_');
    }

    private static string GetParameterName(string name, int index)
    {
        return SyntaxFacts.IsValidIdentifier(name) && name.Length > 0
            ? char.ToLowerInvariant(name[0]) + name.Substring(1)
            : $"parameter{index}";
    }

    private sealed record Parameter
    {
        public Parameter(ISymbol Symbol, ITypeSymbol Type, bool IsWritable)
        {
            this.Symbol = Symbol;
            this.Type = Type;
            this.IsWritable = IsWritable;
        }

        public ISymbol Symbol { get; }
        public ITypeSymbol Type { get; }
        public bool IsWritable { get; }

        public void Deconstruct(out ISymbol Symbol, out ITypeSymbol Type, out bool IsWritable)
        {
            Symbol = this.Symbol;
            Type = this.Type;
            IsWritable = this.IsWritable;
        }
    }
}