<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(ProjectTargetFrameworks)</TargetFrameworks>
    </PropertyGroup>
    
    <ItemGroup>
      <Folder Include="HashFunctions\" />
      <Folder Include="Monosound\" />
      <Folder Include="Polyalphabet\" />
      <Folder Include="Polygramms\" />
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Include="MathForge.Core" Version="1.0.0" />
    </ItemGroup>

</Project>
