<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(ProjectTargetFrameworks)</TargetFrameworks>
    </PropertyGroup>
    
    <ItemGroup>
      <Folder Include="Hashing\" />
      <Folder Include="Monosound\" />
      <Folder Include="Polyalphabet\" />
      <Folder Include="Polygramms\" />
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\MathForge.Core\MathForge.Core.csproj" />
    </ItemGroup>

</Project>
