<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(ProjectTargetFrameworks)</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Sort\Cycle\" />
      <Folder Include="Sort\Distribution\" />
      <Folder Include="Sort\Network\" />
      <Folder Include="Transformation\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MathForge.Core\MathForge.Core.csproj" />
      <ProjectReference Include="..\MathForge.Random\MathForge.Random.csproj" />
    </ItemGroup>
    
</Project>
