<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(ProjectTargetFrameworks)</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Search\" />
      <Folder Include="Sort\" />
      <Folder Include="Transformation\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MathForge.Core" Version="1.0.0" />
    </ItemGroup>
    
</Project>
